name: Firebase Deploy

on:
  push:
    branches: [ main ]
    

jobs:
  build-deploy:
    name: build-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run:  npm install

    - name: build
      run: CI=false && npm run build
      
    - name: Deploy to firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy
      env:
        PROJECT_PATH: ./frontend
        FIREBASE_TOKEN: 1//0gGv0EnymtBIgCgYIARAAGBASNwF-L9IrAaGFDGCRcTz86VE1g7rPfNOc6UalGzne6OwAgkCtKPZxjhQXWEM6etr8jVT_bKGjS34